name: Deploy to AWS (Enigma 3.0)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'
      
      # FIX: pekar pÃ¥ .csproj filen direkt fÃ¶r att slippa varningar
      - name: Publish and Zip
        run: |
          dotnet publish EnigmaAPI/EnigmaAPI.csproj -c Release -o site
          cd site
          zip -r ../site.zip *

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: "eu-north-1"
          application_name: "EnigmaApp"
          environment_name: "EnigmaApp-env"
          version_label: "v3-cyber-${{ github.run_id }}-${{ github.run_attempt }}"
          deployment_package: "site.zip"

      # FIX: Uppdaterad text till V3.0
      - name: Discord Notification
        if: always()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: "ðŸš€ Enigma V3.0 deployed successfully!"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"